# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  
  # TODO: Required for 5G ethernet. Remove once this is the default kernel version
  boot.kernelPackages = pkgs.linuxPackages_6_12;

  boot = {
    initrd = {
      systemd.enable = true;
    };
    loader = {
      efi.canTouchEfiVariables = true;
      # grub = {
      #   enable = true;
      #   device = "nodev";
      #   efiSupport = true;
      # };
    };
    initrd.luks.devices = {
      "cryptkey" = {
        device = "/dev/disk/by-uuid/c93cada0-5b78-4922-8a18-bcec67432932";
	      allowDiscards = true;
      };
      "cryptroot" = {
        device = "/dev/disk/by-uuid/40edc509-941a-4bbd-a436-86ec9703fc18";
        keyFile = "/dev/mapper/cryptkey";
	      keyFileSize = 8192;
	      allowDiscards = true;
      };
    };
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD18-9A84";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/" =
    { device = "nvme-pool/system/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "nvme-pool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "nvme-pool/system/var";
      fsType = "zfs";
    };

  fileSystems."/home/admin" =
    { device = "nvme-pool/user/home/admin";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp118s0u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
